import {Button, InputGroup, Label, ListBox, Select, TextField} from '@heroui-v3/react';
import {UserInputField, UserInputResult} from '@lynx_common/types/plugins/modules';
import filesIpc from '@lynx_shared/ipc/files';
import {File, FolderOpen} from '@solar-icons/react-perf/BoldDuotone';
import {isNil} from 'lodash';
import {Dispatch, FC, SetStateAction, useCallback, useEffect, useState} from 'react';

import LynxSwitch from '../../../../LynxSwitch';

export interface UserInputsProps {
  /** Contains the custom field configuration elements injected by the card module. */
  inputElements: {elements: UserInputField[]; title?: string};
  /** Mutator resolving the current input states back up to the hook processor. */
  setResult: Dispatch<SetStateAction<UserInputResult[]>>;
  /** List of custom functional components representing advanced inputs injected strictly from a sub-extension. */
  extensionElements: FC[] | undefined;
}

/**
 * Displays an arbitrary dynamic form generated by properties mapping standard card fields
 * or extra functional elements injected from external extensions.
 * Follows generic control state linking.
 *
 * @param {UserInputsProps} props - The component props.
 */
export default function UserInputs({inputElements, setResult, extensionElements}: UserInputsProps) {
  const [selectedFolder, setSelectedFolder] = useState<string>('Click here to select folder');
  const [selectedFile, setSelectedFile] = useState<string>('Click here to select file');
  const [errors, setErrors] = useState<Record<string, boolean>>({});

  const updateResult = useCallback(
    (id: string, value: string | boolean) => {
      setResult(prevResult => {
        const newResult = [...prevResult];

        const existingIndex = newResult.findIndex(item => item.id === id);
        if (existingIndex !== -1) {
          newResult[existingIndex] = {id, result: value};
        } else {
          newResult.push({id, result: value});
        }

        return newResult;
      });
    },
    [setResult],
  );

  const updateError = useCallback((id: string, hasError: boolean) => {
    setErrors(prev => ({
      ...prev,
      [id]: hasError,
    }));
  }, []);

  const selectPath = useCallback(
    (type: 'folder' | 'file', id: string, isRequired?: boolean) => {
      switch (type) {
        case 'folder':
          filesIpc.openDlg({properties: ['openDirectory']}).then(result => {
            const folderPath = result || 'Click here to select folder';
            setSelectedFolder(folderPath);
            updateResult(id, result || '');

            // Update error state based on whether selection is valid and required
            if (isRequired) {
              updateError(id, !result || result.trim() === '');
            }
          });
          break;
        case 'file':
          filesIpc.openDlg({properties: ['openFile']}).then(result => {
            const filePath = result || 'Click here to select file';
            setSelectedFile(filePath);
            updateResult(id, result || '');

            // Update error state based on whether selection is valid and required
            if (isRequired) {
              updateError(id, !result || result.trim() === '');
            }
          });
          break;
      }
    },
    [setSelectedFolder, setSelectedFile, updateResult, updateError],
  );

  const onSwitchChange = useCallback(
    (value: boolean, id: string) => {
      updateResult(id, value);
    },
    [updateResult],
  );

  const onInputChange = useCallback(
    (value: string, id: string) => {
      updateResult(id, value);
    },
    [updateResult],
  );

  const onSelectChange = useCallback(
    (value: string, id: string) => {
      updateResult(id, value);
    },
    [updateResult],
  );

  useEffect(() => {
    inputElements.elements.forEach(element => {
      const {id, type, defaultValue} = element;
      if (!isNil(defaultValue)) {
        switch (type) {
          case 'checkbox':
            if (typeof defaultValue === 'boolean') {
              updateResult(id, defaultValue);
            }
            break;
          case 'text-input':
          case 'select':
            if (typeof defaultValue === 'string') {
              updateResult(id, defaultValue);
            }
            break;
          default:
            break;
        }
      }
    });
  }, [inputElements.elements]);

  return (
    <div className="mb-6 mt-4 flex flex-col items-center justify-center gap-y-4 px-2">
      <span className="text-large font-semibold">
        {inputElements.title || 'Please fill in the required information and click Next'}
      </span>
      {inputElements.elements.map(element => {
        const {id, label, type, selectOptions, isRequired, defaultValue} = element;
        const hasError = errors[id] || false;

        switch (type) {
          case 'checkbox':
            return (
              <LynxSwitch
                key={label}
                title={label}
                variant="secondary"
                enabled={!!defaultValue}
                onEnabledChange={value => onSwitchChange(value, id)}
              />
            );
          case 'text-input':
            return (
              <TextField
                variant="secondary"
                isRequired={isRequired}
                onChange={value => onInputChange(value, id)}
                defaultValue={defaultValue as string | undefined}
                fullWidth>
                <Label>{label}</Label>
                <InputGroup>
                  <InputGroup.Input />
                </InputGroup>
              </TextField>
            );
          case 'select':
            return (
              <Select
                onChange={key => {
                  if (key) onSelectChange(key.toString(), id);
                }}
                variant="secondary"
                isRequired={isRequired}
                defaultValue={defaultValue ? (defaultValue as string) : undefined}
                fullWidth>
                <Label>{label}</Label>
                <Select.Trigger>
                  <Select.Value />
                  <Select.Indicator />
                </Select.Trigger>
                <Select.Popover>
                  <ListBox>
                    {selectOptions!.map(option => {
                      return (
                        <ListBox.Item id={option} key={option} textValue={option}>
                          {option}
                          <ListBox.ItemIndicator />
                        </ListBox.Item>
                      );
                    })}
                  </ListBox>
                </Select.Popover>
              </Select>
            );
          case 'directory':
            return (
              <div key={`${label}_div`} className="flex w-full flex-col gap-y-2">
                <Label
                  key={`${label}_text`}
                  className={`text-sm ${isRequired ? 'after:content-["*"] after:text-red-500 after:ml-1' : ''}`}>
                  {label}
                </Label>
                <Button
                  key={label}
                  variant="secondary"
                  onPress={() => selectPath('folder', id, isRequired)}
                  className={`${hasError ? 'border-red-500 border-2' : ''}`}
                  fullWidth>
                  <FolderOpen />
                  <span className={selectedFolder === 'Click here to select folder' && hasError ? 'text-red-500' : ''}>
                    {selectedFolder}
                  </span>
                </Button>
                {hasError && <span className="text-xs text-red-500">{label} is required. Please select a folder.</span>}
              </div>
            );
          case 'file':
            return (
              <div key={`${label}_div`} className="flex w-full flex-col gap-y-2">
                <Label
                  key={`${label}_text`}
                  className={`text-sm ${isRequired ? 'after:content-["*"] after:text-red-500 after:ml-1' : ''}`}>
                  {label}
                </Label>
                <Button
                  key={label}
                  variant="secondary"
                  onPress={() => selectPath('file', id, isRequired)}
                  className={`${hasError ? 'border-red-500 border-2' : ''}`}
                  fullWidth>
                  <File />
                  <span className={selectedFile === 'Click here to select file' && hasError ? 'text-red-500' : ''}>
                    {selectedFile}
                  </span>
                </Button>
                {hasError && <span className="text-xs text-red-500">{label} is required. Please select a file.</span>}
              </div>
            );
        }
      })}

      {extensionElements?.map((Elem, index) => (
        <Elem key={`${index}_extension_userInputElement`} />
      ))}
    </div>
  );
}
